--- name:seabotix
# Matrix of trhuster. Identifie the forces and torques aplied for each of n trhuster
TCM:
  rows: 6
  cols: 4
  data:
  - 1.0 ## surge_right
  - 0.0
  - 0.0
  - 0.0
  - 0.04
  - 0.05
  - 1.0 ## surge_left
  - 0.0
  - 0.0
  - 0.0
  - 0.04
  - -0.05
  - 0.0 ## heave
  - 0.0
  - 1.0
  - 0.0
  - 0.4
  - 0.0
  - 0.0 ## sway
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  - 0.01
# If left empty, uses RAW by default
control_modes: 
  - RAW
  - RAW
  - RAW
  - RAW
# no documentation available for this property
metadata:
  metadata: []
  properties: []
  input_ports: []
  output_ports: []
# Names of the thrusters
# Leave empty to use no names
names: ["surge_right", "surge_left", "heave", "sway"]
# The amount of actuators the vehicle has
number_of_thruster: 4
# In case the control mode is PWM, used to convert the signal into DC Voltage
thrusterVoltage: 19.0
# Convert thruster signal into forces, in negative direction. Should have the size of amount_of_actuators
thruster_coefficients_Neg:
  data: 
  - 0.031524 #0.051854 #0.03457 #0.031524 
  - 0.031524
  - 0.031524
  - 0.031524   
# Convert thruster signal into forces, in positive direction. Should have the size of amount_of_actuators
thruster_coefficients_Pos:
  data: 
  - 0.039675  #0.052081 #0.04005 #0.039675 
  - 0.039675
  - 0.039675
  - 0.039675
  
  

